<?php

use Illuminate\Database\Seeder;

class HrmsInstituteCreateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('institutes')->insert([
			['education_level_id'=>'2','institute_name'=>'Ahsanullah University of Science and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'American International University-Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'ASA University Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Asian University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Atish Dipankar University of Science and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangabandhu Sheikh Mujib Medical University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangabandhu Sheikh Mujibur Rahman Agricultural University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangabandhu Sheikh Mujibur Rahman Maritime University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangabandhu Sheikh Mujibur Rahman Science and Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh Agricultural University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh Islami University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh University of Business and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh University of Engineering and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh University of Professionals', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Bangladesh University of Textiles', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Begum Gulchemonara Trust University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Begum Rokeya University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'BRAC University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Chittagong University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Chittagong University of Engineering and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Chittagong Veterinary and Animal Sciences University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'City University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Comilla University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Coxs Bazar International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Daffodil International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Darul Ihsan University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Dhaka International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Dhaka University of Engineering & Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'East Delta University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'East West University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Eastern University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'European University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Gono Bishwabidyalay', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Green University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Hajee Mohammad Danesh Science and Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'IBAIS University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Independent University, Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'International Islamic University, Chittagong', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'International University of Business Agriculture and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Islamic University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Islamic University of Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Jagannath University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Jahangirnagar University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Jatiya Kabi Kazi Nazrul Islam University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Jessore University of Science and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Khulna University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Khulna University of Engineering and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Khwaja Yunus Ali University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Leading University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Manarat International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Mawlana Bhashani Science and Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Metropolitan University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'National University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Noakhali Science and Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'North South University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'North Western University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Northern University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Notre Dame University Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Pabna Science & Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Patuakhali Science and Technology University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Port City International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Premier University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Presidency University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Prime University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Primeasia University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Rajshahi University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Rajshahi University of Engineering and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Rangamati University of Science & Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Royal University of Dhaka', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Shahjalal University of Science and Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Shanto Mariam University of Creative Technology', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Sher-e-Bangla Agricultural University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Sonargaon University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Southeast University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Southern University Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Stamford University Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'State University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Sylhet Agricultural University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Sylhet International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'The Millenium University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'The Peoples University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'The University of Asia Pacific', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'United International University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Barisal', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Development Alternative', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Dhaka', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Information Technology and Sciences', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Liberal Arts Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of Science and Technology Chittagong', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'University of South Asia', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Uttara University', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'Victoria University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'2','institute_name'=>'World University of Bangladesh', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Barisal', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Chittagong', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Comilla', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Dhaka', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Dinajpur', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Jessore', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Rajshahi', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Sylhet', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Madrasah', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'Technical', 'status'=>'1'],
			['education_level_id'=>'1','institute_name'=>'DIBS (Dhaka)', 'status'=>'1'],
    	]);
    }
}
