<?php

use Illuminate\Database\Seeder;

class HrmsPoliceStationCreateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('police_stations')->insert([
            ['district_id'=>'34', 'police_station_name'=>'Amtali Upazila', 'police_station_bn_name'=>'আমতলী'],
            ['district_id'=>'34', 'police_station_name'=>'Bamna Upazila', 'police_station_bn_name'=>'বামনা'],
            ['district_id'=>'34', 'police_station_name'=>'Barguna Sadar Upazila', 'police_station_bn_name'=>'বরগুনা সদর'],
            ['district_id'=>'34', 'police_station_name'=>'Betagi Upazila', 'police_station_bn_name'=>'বেতাগি'],
            ['district_id'=>'34', 'police_station_name'=>'Patharghata Upazila', 'police_station_bn_name'=>'পাথরঘাটা'],
            ['district_id'=>'34', 'police_station_name'=>'Taltali Upazila', 'police_station_bn_name'=>'তালতলী'],
            ['district_id'=>'35', 'police_station_name'=>'Muladi Upazila', 'police_station_bn_name'=>'মুলাদি'],
            ['district_id'=>'35', 'police_station_name'=>'Babuganj Upazila', 'police_station_bn_name'=>'বাবুগঞ্জ'],
            ['district_id'=>'35', 'police_station_name'=>'Agailjhara Upazila', 'police_station_bn_name'=>'আগাইলঝরা'],
            ['district_id'=>'35', 'police_station_name'=>'Barisal Sadar Upazila', 'police_station_bn_name'=>'বরিশাল সদর'],
            ['district_id'=>'35', 'police_station_name'=>'Bakerganj Upazila', 'police_station_bn_name'=>'বাকেরগঞ্জ'],
            ['district_id'=>'35', 'police_station_name'=>'Banaripara Upazila', 'police_station_bn_name'=>'বানাড়িপারা'],
            ['district_id'=>'35', 'police_station_name'=>'Gaurnadi Upazila', 'police_station_bn_name'=>'গৌরনদী'],
            ['district_id'=>'35', 'police_station_name'=>'Hizla Upazila', 'police_station_bn_name'=>'হিজলা'],
            ['district_id'=>'35', 'police_station_name'=>'Mehendiganj Upazila', 'police_station_bn_name'=>'মেহেদিগঞ্জ '],
            ['district_id'=>'35', 'police_station_name'=>'Wazirpur Upazila', 'police_station_bn_name'=>'ওয়াজিরপুর'],
            ['district_id'=>'36', 'police_station_name'=>'Bhola Sadar Upazila', 'police_station_bn_name'=>'ভোলা সদর'],
            ['district_id'=>'36', 'police_station_name'=>'Burhanuddin Upazila', 'police_station_bn_name'=>'বুরহানউদ্দিন'],
            ['district_id'=>'36', 'police_station_name'=>'Char Fasson Upazila', 'police_station_bn_name'=>'চর ফ্যাশন'],
            ['district_id'=>'36', 'police_station_name'=>'Daulatkhan Upazila', 'police_station_bn_name'=>'দৌলতখান'],
            ['district_id'=>'36', 'police_station_name'=>'Lalmohan Upazila', 'police_station_bn_name'=>'লালমোহন'],
            ['district_id'=>'36', 'police_station_name'=>'Manpura Upazila', 'police_station_bn_name'=>'মনপুরা'],
            ['district_id'=>'36', 'police_station_name'=>'Tazumuddin Upazila', 'police_station_bn_name'=>'তাজুমুদ্দিন'],
            ['district_id'=>'37', 'police_station_name'=>'Jhalokati Sadar Upazila', 'police_station_bn_name'=>'ঝালকাঠি সদর'],
            ['district_id'=>'37', 'police_station_name'=>'Kathalia Upazila', 'police_station_bn_name'=>'কাঁঠালিয়া'],
            ['district_id'=>'37', 'police_station_name'=>'Nalchity Upazila', 'police_station_bn_name'=>'নালচিতি'],
            ['district_id'=>'37', 'police_station_name'=>'Rajapur Upazila', 'police_station_bn_name'=>'রাজাপুর'],
            ['district_id'=>'38', 'police_station_name'=>'Bauphal Upazila', 'police_station_bn_name'=>'বাউফল'],
            ['district_id'=>'38', 'police_station_name'=>'Dashmina Upazila', 'police_station_bn_name'=>'দশমিনা'],
            ['district_id'=>'38', 'police_station_name'=>'Galachipa Upazila', 'police_station_bn_name'=>'গলাচিপা'],
            ['district_id'=>'38', 'police_station_name'=>'Kalapara Upazila', 'police_station_bn_name'=>'কালাপারা'],
            ['district_id'=>'38', 'police_station_name'=>'Mirzaganj Upazila', 'police_station_bn_name'=>'মির্জাগঞ্জ '],
            ['district_id'=>'38', 'police_station_name'=>'Patuakhali Sadar Upazila', 'police_station_bn_name'=>'পটুয়াখালী সদর'],
            ['district_id'=>'38', 'police_station_name'=>'Dumki Upazila', 'police_station_bn_name'=>'ডুমকি'],
            ['district_id'=>'38', 'police_station_name'=>'Rangabali Upazila', 'police_station_bn_name'=>'রাঙ্গাবালি'],
            ['district_id'=>'39', 'police_station_name'=>'Bhandaria', 'police_station_bn_name'=>'ভ্যান্ডারিয়া'],
            ['district_id'=>'39', 'police_station_name'=>'Kaukhali', 'police_station_bn_name'=>'কাউখালি'],
            ['district_id'=>'39', 'police_station_name'=>'Mathbaria', 'police_station_bn_name'=>'মাঠবাড়িয়া'],
            ['district_id'=>'39', 'police_station_name'=>'Nazirpur', 'police_station_bn_name'=>'নাজিরপুর'],
            ['district_id'=>'39', 'police_station_name'=>'Nesarabad', 'police_station_bn_name'=>'নেসারাবাদ'],
            ['district_id'=>'39', 'police_station_name'=>'Pirojpur Sadar', 'police_station_bn_name'=>'পিরোজপুর সদর'],
            ['district_id'=>'39', 'police_station_name'=>'Zianagar', 'police_station_bn_name'=>'জিয়ানগর'],
            ['district_id'=>'40', 'police_station_name'=>'Bandarban Sadar', 'police_station_bn_name'=>'বান্দরবন সদর'],
            ['district_id'=>'40', 'police_station_name'=>'Thanchi', 'police_station_bn_name'=>'থানচি'],
            ['district_id'=>'40', 'police_station_name'=>'Lama', 'police_station_bn_name'=>'লামা'],
            ['district_id'=>'40', 'police_station_name'=>'Naikhongchhari', 'police_station_bn_name'=>'নাইখংছড়ি '],
            ['district_id'=>'40', 'police_station_name'=>'Ali kadam', 'police_station_bn_name'=>'আলী কদম'],
            ['district_id'=>'40', 'police_station_name'=>'Rowangchhari', 'police_station_bn_name'=>'রউয়াংছড়ি '],
            ['district_id'=>'40', 'police_station_name'=>'Ruma', 'police_station_bn_name'=>'রুমা'],
            ['district_id'=>'41', 'police_station_name'=>'Brahmanbaria Sadar Upazila', 'police_station_bn_name'=>'ব্রাহ্মণবাড়িয়া সদর'],
            ['district_id'=>'41', 'police_station_name'=>'Ashuganj Upazila', 'police_station_bn_name'=>'আশুগঞ্জ'],
            ['district_id'=>'41', 'police_station_name'=>'Nasirnagar Upazila', 'police_station_bn_name'=>'নাসির নগর'],
            ['district_id'=>'41', 'police_station_name'=>'Nabinagar Upazila', 'police_station_bn_name'=>'নবীনগর'],
            ['district_id'=>'41', 'police_station_name'=>'Sarail Upazila', 'police_station_bn_name'=>'সরাইল'],
            ['district_id'=>'41', 'police_station_name'=>'Shahbazpur Town', 'police_station_bn_name'=>'শাহবাজপুর টাউন'],
            ['district_id'=>'41', 'police_station_name'=>'Kasba Upazila', 'police_station_bn_name'=>'কসবা'],
            ['district_id'=>'41', 'police_station_name'=>'Akhaura Upazila', 'police_station_bn_name'=>'আখাউরা'],
            ['district_id'=>'41', 'police_station_name'=>'Bancharampur Upazila', 'police_station_bn_name'=>'বাঞ্ছারামপুর'],
            ['district_id'=>'41', 'police_station_name'=>'Bijoynagar Upazila', 'police_station_bn_name'=>'বিজয় নগর'],
            ['district_id'=>'42', 'police_station_name'=>'Chandpur Sadar', 'police_station_bn_name'=>'চাঁদপুর সদর'],
            ['district_id'=>'42', 'police_station_name'=>'Faridganj', 'police_station_bn_name'=>'ফরিদগঞ্জ'],
            ['district_id'=>'42', 'police_station_name'=>'Haimchar', 'police_station_bn_name'=>'হাইমচর'],
            ['district_id'=>'42', 'police_station_name'=>'Haziganj', 'police_station_bn_name'=>'হাজীগঞ্জ'],
            ['district_id'=>'42', 'police_station_name'=>'Kachua', 'police_station_bn_name'=>'কচুয়া'],
            ['district_id'=>'42', 'police_station_name'=>'Matlab Uttar', 'police_station_bn_name'=>'মতলব উত্তর'],
            ['district_id'=>'42', 'police_station_name'=>'Matlab Dakkhin', 'police_station_bn_name'=>'মতলব দক্ষিণ'],
            ['district_id'=>'42', 'police_station_name'=>'Shahrasti', 'police_station_bn_name'=>'শাহরাস্তি'],
            ['district_id'=>'43', 'police_station_name'=>'Anwara Upazila', 'police_station_bn_name'=>'আনোয়ারা'],
            ['district_id'=>'43', 'police_station_name'=>'Banshkhali Upazila', 'police_station_bn_name'=>'বাশখালি'],
            ['district_id'=>'43', 'police_station_name'=>'Boalkhali Upazila', 'police_station_bn_name'=>'বোয়ালখালি'],
            ['district_id'=>'43', 'police_station_name'=>'Chandanaish Upazila', 'police_station_bn_name'=>'চন্দনাইশ'],
            ['district_id'=>'43', 'police_station_name'=>'Fatikchhari Upazila', 'police_station_bn_name'=>'ফটিকছড়ি'],
            ['district_id'=>'43', 'police_station_name'=>'Hathazari Upazila', 'police_station_bn_name'=>'হাঠহাজারী'],
            ['district_id'=>'43', 'police_station_name'=>'Lohagara Upazila', 'police_station_bn_name'=>'লোহাগারা'],
            ['district_id'=>'43', 'police_station_name'=>'Mirsharai Upazila', 'police_station_bn_name'=>'মিরসরাই'],
            ['district_id'=>'43', 'police_station_name'=>'Patiya Upazila', 'police_station_bn_name'=>'পটিয়া'],
            ['district_id'=>'43', 'police_station_name'=>'Rangunia Upazila', 'police_station_bn_name'=>'রাঙ্গুনিয়া'],
            ['district_id'=>'43', 'police_station_name'=>'Raozan Upazila', 'police_station_bn_name'=>'রাউজান'],
            ['district_id'=>'43', 'police_station_name'=>'Sandwip Upazila', 'police_station_bn_name'=>'সন্দ্বীপ'],
            ['district_id'=>'43', 'police_station_name'=>'Satkania Upazila', 'police_station_bn_name'=>'সাতকানিয়া'],
            ['district_id'=>'43', 'police_station_name'=>'Sitakunda Upazila', 'police_station_bn_name'=>'সীতাকুণ্ড'],
            ['district_id'=>'44', 'police_station_name'=>'Barura Upazila', 'police_station_bn_name'=>'বড়ুরা'],
            ['district_id'=>'44', 'police_station_name'=>'Brahmanpara Upazila', 'police_station_bn_name'=>'ব্রাহ্মণপাড়া'],
            ['district_id'=>'44', 'police_station_name'=>'Burichong Upazila', 'police_station_bn_name'=>'বুড়িচং'],
            ['district_id'=>'44', 'police_station_name'=>'Chandina Upazila', 'police_station_bn_name'=>'চান্দিনা'],
            ['district_id'=>'44', 'police_station_name'=>'Chauddagram Upazila', 'police_station_bn_name'=>'চৌদ্দগ্রাম'],
            ['district_id'=>'44', 'police_station_name'=>'Daudkandi Upazila', 'police_station_bn_name'=>'দাউদকান্দি'],
            ['district_id'=>'44', 'police_station_name'=>'Debidwar Upazila', 'police_station_bn_name'=>'দেবীদ্বার'],
            ['district_id'=>'44', 'police_station_name'=>'Homna Upazila', 'police_station_bn_name'=>'হোমনা'],
            ['district_id'=>'44', 'police_station_name'=>'Comilla Sadar Upazila', 'police_station_bn_name'=>'কুমিল্লা সদর'],
            ['district_id'=>'44', 'police_station_name'=>'Laksam Upazila', 'police_station_bn_name'=>'লাকসাম'],
            ['district_id'=>'44', 'police_station_name'=>'Monohorgonj Upazila', 'police_station_bn_name'=>'মনোহরগঞ্জ'],
            ['district_id'=>'44', 'police_station_name'=>'Meghna Upazila', 'police_station_bn_name'=>'মেঘনা'],
            ['district_id'=>'44', 'police_station_name'=>'Muradnagar Upazila', 'police_station_bn_name'=>'মুরাদনগর'],
            ['district_id'=>'44', 'police_station_name'=>'Nangalkot Upazila', 'police_station_bn_name'=>'নাঙ্গালকোট'],
            ['district_id'=>'44', 'police_station_name'=>'Comilla Sadar South Upazila', 'police_station_bn_name'=>'কুমিল্লা সদর দক্ষিণ'],
            ['district_id'=>'44', 'police_station_name'=>'Titas Upazila', 'police_station_bn_name'=>'তিতাস'],
            ['district_id'=>'45', 'police_station_name'=>'Chakaria Upazila', 'police_station_bn_name'=>'চকরিয়া'],
            ['district_id'=>'45', 'police_station_name'=>'Chakaria Upazila', 'police_station_bn_name'=>'চকরিয়া'],
            ['district_id'=>'45', 'police_station_name'=>'Coxs Bazar Sadar Upazila', 'police_station_bn_name'=>'কক্স বাজার সদর'],
            ['district_id'=>'45', 'police_station_name'=>'Kutubdia Upazila', 'police_station_bn_name'=>'কুতুবদিয়া'],
            ['district_id'=>'45', 'police_station_name'=>'Maheshkhali Upazila', 'police_station_bn_name'=>'মহেশখালী'],
            ['district_id'=>'45', 'police_station_name'=>'Ramu Upazila', 'police_station_bn_name'=>'রামু'],
            ['district_id'=>'45', 'police_station_name'=>'Teknaf Upazila', 'police_station_bn_name'=>'টেকনাফ'],
            ['district_id'=>'45', 'police_station_name'=>'Ukhia Upazila', 'police_station_bn_name'=>'উখিয়া'],
            ['district_id'=>'45', 'police_station_name'=>'Pekua Upazila', 'police_station_bn_name'=>'পেকুয়া'],
            ['district_id'=>'46', 'police_station_name'=>'Feni Sadar', 'police_station_bn_name'=>'ফেনী সদর'],
            ['district_id'=>'46', 'police_station_name'=>'Chagalnaiya', 'police_station_bn_name'=>'ছাগল নাইয়া'],
            ['district_id'=>'46', 'police_station_name'=>'Daganbhyan', 'police_station_bn_name'=>'দাগানভিয়া'],
            ['district_id'=>'46', 'police_station_name'=>'Parshuram', 'police_station_bn_name'=>'পরশুরাম'],
            ['district_id'=>'46', 'police_station_name'=>'Fhulgazi', 'police_station_bn_name'=>'ফুলগাজি'],
            ['district_id'=>'46', 'police_station_name'=>'Sonagazi', 'police_station_bn_name'=>'সোনাগাজি'],
            ['district_id'=>'47', 'police_station_name'=>'Dighinala Upazila', 'police_station_bn_name'=>'দিঘিনালা '],
            ['district_id'=>'47', 'police_station_name'=>'Khagrachhari Upazila', 'police_station_bn_name'=>'খাগড়াছড়ি'],
            ['district_id'=>'47', 'police_station_name'=>'Lakshmichhari Upazila', 'police_station_bn_name'=>'লক্ষ্মীছড়ি'],
            ['district_id'=>'47', 'police_station_name'=>'Mahalchhari Upazila', 'police_station_bn_name'=>'মহলছড়ি'],
            ['district_id'=>'47', 'police_station_name'=>'Manikchhari Upazila', 'police_station_bn_name'=>'মানিকছড়ি'],
            ['district_id'=>'47', 'police_station_name'=>'Matiranga Upazila', 'police_station_bn_name'=>'মাটিরাঙ্গা'],
            ['district_id'=>'47', 'police_station_name'=>'Panchhari Upazila', 'police_station_bn_name'=>'পানছড়ি'],
            ['district_id'=>'47', 'police_station_name'=>'Ramgarh Upazila', 'police_station_bn_name'=>'রামগড়'],
            ['district_id'=>'48', 'police_station_name'=>'Lakshmipur Sadar Upazila', 'police_station_bn_name'=>'লক্ষ্মীপুর সদর'],
            ['district_id'=>'48', 'police_station_name'=>'Raipur Upazila', 'police_station_bn_name'=>'রায়পুর'],
            ['district_id'=>'48', 'police_station_name'=>'Ramganj Upazila', 'police_station_bn_name'=>'রামগঞ্জ'],
            ['district_id'=>'48', 'police_station_name'=>'Ramgati Upazila', 'police_station_bn_name'=>'রামগতি'],
            ['district_id'=>'48', 'police_station_name'=>'Komol Nagar Upazila', 'police_station_bn_name'=>'কমল নগর'],
            ['district_id'=>'49', 'police_station_name'=>'Noakhali Sadar Upazila', 'police_station_bn_name'=>'নোয়াখালী সদর'],
            ['district_id'=>'49', 'police_station_name'=>'Begumganj Upazila', 'police_station_bn_name'=>'বেগমগঞ্জ'],
            ['district_id'=>'49', 'police_station_name'=>'Chatkhil Upazila', 'police_station_bn_name'=>'চাটখিল'],
            ['district_id'=>'49', 'police_station_name'=>'Companyganj Upazila', 'police_station_bn_name'=>'কোম্পানীগঞ্জ'],
            ['district_id'=>'49', 'police_station_name'=>'Shenbag Upazila', 'police_station_bn_name'=>'শেনবাগ'],
            ['district_id'=>'49', 'police_station_name'=>'Hatia Upazila', 'police_station_bn_name'=>'হাতিয়া'],
            ['district_id'=>'49', 'police_station_name'=>'Kobirhat Upazila', 'police_station_bn_name'=>'কবিরহাট '],
            ['district_id'=>'49', 'police_station_name'=>'Sonaimuri Upazila', 'police_station_bn_name'=>'সোনাইমুরি'],
            ['district_id'=>'49', 'police_station_name'=>'Suborno Char Upazila', 'police_station_bn_name'=>'সুবর্ণ চর '],
            ['district_id'=>'50', 'police_station_name'=>'Rangamati Sadar Upazila', 'police_station_bn_name'=>'রাঙ্গামাটি সদর'],
            ['district_id'=>'50', 'police_station_name'=>'Belaichhari Upazila', 'police_station_bn_name'=>'বেলাইছড়ি'],
            ['district_id'=>'50', 'police_station_name'=>'Bagaichhari Upazila', 'police_station_bn_name'=>'বাঘাইছড়ি'],
            ['district_id'=>'50', 'police_station_name'=>'Barkal Upazila', 'police_station_bn_name'=>'বরকল'],
            ['district_id'=>'50', 'police_station_name'=>'Juraichhari Upazila', 'police_station_bn_name'=>'জুরাইছড়ি'],
            ['district_id'=>'50', 'police_station_name'=>'Rajasthali Upazila', 'police_station_bn_name'=>'রাজাস্থলি'],
            ['district_id'=>'50', 'police_station_name'=>'Kaptai Upazila', 'police_station_bn_name'=>'কাপ্তাই'],
            ['district_id'=>'50', 'police_station_name'=>'Langadu Upazila', 'police_station_bn_name'=>'লাঙ্গাডু'],
            ['district_id'=>'50', 'police_station_name'=>'Nannerchar Upazila', 'police_station_bn_name'=>'নান্নেরচর '],
            ['district_id'=>'50', 'police_station_name'=>'Kaukhali Upazila', 'police_station_bn_name'=>'কাউখালি'],
            ['district_id'=>'1', 'police_station_name'=>'Dhamrai Upazila', 'police_station_bn_name'=>'ধামরাই'],
            ['district_id'=>'1', 'police_station_name'=>'Dohar Upazila', 'police_station_bn_name'=>'দোহার'],
            ['district_id'=>'1', 'police_station_name'=>'Keraniganj Upazila', 'police_station_bn_name'=>'কেরানীগঞ্জ'],
            ['district_id'=>'1', 'police_station_name'=>'Nawabganj Upazila', 'police_station_bn_name'=>'নবাবগঞ্জ'],
            ['district_id'=>'1', 'police_station_name'=>'Savar Upazila', 'police_station_bn_name'=>'সাভার'],
            ['district_id'=>'2', 'police_station_name'=>'Faridpur Sadar Upazila', 'police_station_bn_name'=>'ফরিদপুর সদর'],
            ['district_id'=>'2', 'police_station_name'=>'Boalmari Upazila', 'police_station_bn_name'=>'বোয়ালমারী'],
            ['district_id'=>'2', 'police_station_name'=>'Alfadanga Upazila', 'police_station_bn_name'=>'আলফাডাঙ্গা'],
            ['district_id'=>'2', 'police_station_name'=>'Madhukhali Upazila', 'police_station_bn_name'=>'মধুখালি'],
            ['district_id'=>'2', 'police_station_name'=>'Bhanga Upazila', 'police_station_bn_name'=>'ভাঙ্গা'],
            ['district_id'=>'2', 'police_station_name'=>'Nagarkanda Upazila', 'police_station_bn_name'=>'নগরকান্ড'],
            ['district_id'=>'2', 'police_station_name'=>'Charbhadrasan Upazila', 'police_station_bn_name'=>'চরভদ্রাসন '],
            ['district_id'=>'2', 'police_station_name'=>'Sadarpur Upazila', 'police_station_bn_name'=>'সদরপুর'],
            ['district_id'=>'2', 'police_station_name'=>'Shaltha Upazila', 'police_station_bn_name'=>'শালথা'],
            ['district_id'=>'3', 'police_station_name'=>'Gazipur Sadar-Joydebpur', 'police_station_bn_name'=>'গাজীপুর সদর'],
            ['district_id'=>'3', 'police_station_name'=>'Kaliakior', 'police_station_bn_name'=>'কালিয়াকৈর'],
            ['district_id'=>'3', 'police_station_name'=>'Kapasia', 'police_station_bn_name'=>'কাপাসিয়া'],
            ['district_id'=>'3', 'police_station_name'=>'Sripur', 'police_station_bn_name'=>'শ্রীপুর'],
            ['district_id'=>'3', 'police_station_name'=>'Kaliganj', 'police_station_bn_name'=>'কালীগঞ্জ'],
            ['district_id'=>'3', 'police_station_name'=>'Tongi', 'police_station_bn_name'=>'টঙ্গি'],
            ['district_id'=>'4', 'police_station_name'=>'Gopalganj Sadar Upazila', 'police_station_bn_name'=>'গোপালগঞ্জ সদর'],
            ['district_id'=>'4', 'police_station_name'=>'Kashiani Upazila', 'police_station_bn_name'=>'কাশিয়ানি'],
            ['district_id'=>'4', 'police_station_name'=>'Kotalipara Upazila', 'police_station_bn_name'=>'কোটালিপাড়া'],
            ['district_id'=>'4', 'police_station_name'=>'Muksudpur Upazila', 'police_station_bn_name'=>'মুকসুদপুর'],
            ['district_id'=>'4', 'police_station_name'=>'Tungipara Upazila', 'police_station_bn_name'=>'টুঙ্গিপাড়া'],
            ['district_id'=>'5', 'police_station_name'=>'Dewanganj Upazila', 'police_station_bn_name'=>'দেওয়ানগঞ্জ'],
            ['district_id'=>'5', 'police_station_name'=>'Baksiganj Upazila', 'police_station_bn_name'=>'বকসিগঞ্জ'],
            ['district_id'=>'5', 'police_station_name'=>'Islampur Upazila', 'police_station_bn_name'=>'ইসলামপুর'],
            ['district_id'=>'5', 'police_station_name'=>'Jamalpur Sadar Upazila', 'police_station_bn_name'=>'জামালপুর সদর'],
            ['district_id'=>'5', 'police_station_name'=>'Madarganj Upazila', 'police_station_bn_name'=>'মাদারগঞ্জ'],
            ['district_id'=>'5', 'police_station_name'=>'Melandaha Upazila', 'police_station_bn_name'=>'মেলানদাহা'],
            ['district_id'=>'5', 'police_station_name'=>'Sarishabari Upazila', 'police_station_bn_name'=>'সরিষাবাড়ি '],
            ['district_id'=>'5', 'police_station_name'=>'Narundi Police I.C', 'police_station_bn_name'=>'নারুন্দি'],
            ['district_id'=>'6', 'police_station_name'=>'Astagram Upazila', 'police_station_bn_name'=>'অষ্টগ্রাম'],
            ['district_id'=>'6', 'police_station_name'=>'Bajitpur Upazila', 'police_station_bn_name'=>'বাজিতপুর'],
            ['district_id'=>'6', 'police_station_name'=>'Bhairab Upazila', 'police_station_bn_name'=>'ভৈরব'],
            ['district_id'=>'6', 'police_station_name'=>'Hossainpur Upazila', 'police_station_bn_name'=>'হোসেনপুর '],
            ['district_id'=>'6', 'police_station_name'=>'Itna Upazila', 'police_station_bn_name'=>'ইটনা'],
            ['district_id'=>'6', 'police_station_name'=>'Karimganj Upazila', 'police_station_bn_name'=>'করিমগঞ্জ'],
            ['district_id'=>'6', 'police_station_name'=>'Katiadi Upazila', 'police_station_bn_name'=>'কতিয়াদি'],
            ['district_id'=>'6', 'police_station_name'=>'Kishoreganj Sadar Upazila', 'police_station_bn_name'=>'কিশোরগঞ্জ সদর'],
            ['district_id'=>'6', 'police_station_name'=>'Kuliarchar Upazila', 'police_station_bn_name'=>'কুলিয়ারচর'],
            ['district_id'=>'6', 'police_station_name'=>'Mithamain Upazila', 'police_station_bn_name'=>'মিঠামাইন'],
            ['district_id'=>'6', 'police_station_name'=>'Nikli Upazila', 'police_station_bn_name'=>'নিকলি'],
            ['district_id'=>'6', 'police_station_name'=>'Pakundia Upazila', 'police_station_bn_name'=>'পাকুন্ডা'],
            ['district_id'=>'6', 'police_station_name'=>'Tarail Upazila', 'police_station_bn_name'=>'তাড়াইল'],
            ['district_id'=>'7', 'police_station_name'=>'Madaripur Sadar', 'police_station_bn_name'=>'মাদারীপুর সদর'],
            ['district_id'=>'7', 'police_station_name'=>'Kalkini', 'police_station_bn_name'=>'কালকিনি'],
            ['district_id'=>'7', 'police_station_name'=>'Rajoir', 'police_station_bn_name'=>'রাজইর'],
            ['district_id'=>'7', 'police_station_name'=>'Shibchar', 'police_station_bn_name'=>'শিবচর'],
            ['district_id'=>'8', 'police_station_name'=>'Manikganj Sadar Upazila', 'police_station_bn_name'=>'মানিকগঞ্জ সদর'],
            ['district_id'=>'8', 'police_station_name'=>'Singair Upazila', 'police_station_bn_name'=>'সিঙ্গাইর'],
            ['district_id'=>'8', 'police_station_name'=>'Shibalaya Upazila', 'police_station_bn_name'=>'শিবালয়'],
            ['district_id'=>'8', 'police_station_name'=>'Saturia Upazila', 'police_station_bn_name'=>'সাঠুরিয়া'],
            ['district_id'=>'8', 'police_station_name'=>'Harirampur Upazila', 'police_station_bn_name'=>'হরিরামপুর'],
            ['district_id'=>'8', 'police_station_name'=>'Ghior Upazila', 'police_station_bn_name'=>'ঘিওর'],
            ['district_id'=>'8', 'police_station_name'=>'Daulatpur Upazila', 'police_station_bn_name'=>'দৌলতপুর'],
            ['district_id'=>'9', 'police_station_name'=>'Lohajang Upazila', 'police_station_bn_name'=>'লোহাজং'],
            ['district_id'=>'9', 'police_station_name'=>'Sreenagar Upazila', 'police_station_bn_name'=>'শ্রীনগর'],
            ['district_id'=>'9', 'police_station_name'=>'Munshiganj Sadar Upazila', 'police_station_bn_name'=>'মুন্সিগঞ্জ সদর'],
            ['district_id'=>'9', 'police_station_name'=>'Sirajdikhan Upazila', 'police_station_bn_name'=>'সিরাজদিখান'],
            ['district_id'=>'9', 'police_station_name'=>'Tongibari Upazila', 'police_station_bn_name'=>'টঙ্গিবাড়ি'],
            ['district_id'=>'9', 'police_station_name'=>'Gazaria Upazila', 'police_station_bn_name'=>'গজারিয়া'],
            ['district_id'=>'10', 'police_station_name'=>'Bhaluka', 'police_station_bn_name'=>'ভালুকা'],
            ['district_id'=>'10', 'police_station_name'=>'Trishal', 'police_station_bn_name'=>'ত্রিশাল'],
            ['district_id'=>'10', 'police_station_name'=>'Haluaghat', 'police_station_bn_name'=>'হালুয়াঘাট'],
            ['district_id'=>'10', 'police_station_name'=>'Muktagachha', 'police_station_bn_name'=>'মুক্তাগাছা'],
            ['district_id'=>'10', 'police_station_name'=>'Dhobaura', 'police_station_bn_name'=>'ধবারুয়া'],
            ['district_id'=>'10', 'police_station_name'=>'Fulbaria', 'police_station_bn_name'=>'ফুলবাড়িয়া'],
            ['district_id'=>'10', 'police_station_name'=>'Gaffargaon', 'police_station_bn_name'=>'গফরগাঁও'],
            ['district_id'=>'10', 'police_station_name'=>'Gauripur', 'police_station_bn_name'=>'গৌরিপুর'],
            ['district_id'=>'10', 'police_station_name'=>'Ishwarganj', 'police_station_bn_name'=>'ঈশ্বরগঞ্জ'],
            ['district_id'=>'10', 'police_station_name'=>'Mymensingh Sadar', 'police_station_bn_name'=>'ময়মনসিং সদর'],
            ['district_id'=>'10', 'police_station_name'=>'Nandail', 'police_station_bn_name'=>'নন্দাইল'],
            ['district_id'=>'10', 'police_station_name'=>'Phulpur', 'police_station_bn_name'=>'ফুলপুর'],
            ['district_id'=>'11', 'police_station_name'=>'Araihazar Upazila', 'police_station_bn_name'=>'আড়াইহাজার'],
            ['district_id'=>'11', 'police_station_name'=>'Sonargaon Upazila', 'police_station_bn_name'=>'সোনারগাঁও'],
            ['district_id'=>'11', 'police_station_name'=>'Bandar', 'police_station_bn_name'=>'বান্দার'],
            ['district_id'=>'11', 'police_station_name'=>'Naryanganj Sadar Upazila', 'police_station_bn_name'=>'নারায়ানগঞ্জ সদর'],
            ['district_id'=>'11', 'police_station_name'=>'Rupganj Upazila', 'police_station_bn_name'=>'রূপগঞ্জ'],
            ['district_id'=>'11', 'police_station_name'=>'Siddirgonj Upazila', 'police_station_bn_name'=>'সিদ্ধিরগঞ্জ'],
            ['district_id'=>'12', 'police_station_name'=>'Belabo Upazila', 'police_station_bn_name'=>'বেলাবো'],
            ['district_id'=>'12', 'police_station_name'=>'Monohardi Upazila', 'police_station_bn_name'=>'মনোহরদি'],
            ['district_id'=>'12', 'police_station_name'=>'Narsingdi Sadar Upazila', 'police_station_bn_name'=>'নরসিংদী সদর'],
            ['district_id'=>'12', 'police_station_name'=>'Palash Upazila', 'police_station_bn_name'=>'পলাশ'],
            ['district_id'=>'12', 'police_station_name'=>'Raipura Upazila, Narsingdi', 'police_station_bn_name'=>'রায়পুর'],
            ['district_id'=>'12', 'police_station_name'=>'Shibpur Upazila', 'police_station_bn_name'=>'শিবপুর'],
            ['district_id'=>'13', 'police_station_name'=>'Kendua Upazilla', 'police_station_bn_name'=>'কেন্দুয়া'],
            ['district_id'=>'13', 'police_station_name'=>'Atpara Upazilla', 'police_station_bn_name'=>'আটপাড়া'],
            ['district_id'=>'13', 'police_station_name'=>'Barhatta Upazilla', 'police_station_bn_name'=>'বরহাট্টা'],
            ['district_id'=>'13', 'police_station_name'=>'Durgapur Upazilla', 'police_station_bn_name'=>'দুর্গাপুর'],
            ['district_id'=>'13', 'police_station_name'=>'Kalmakanda Upazilla', 'police_station_bn_name'=>'কলমাকান্দা'],
            ['district_id'=>'13', 'police_station_name'=>'Madan Upazilla', 'police_station_bn_name'=>'মদন'],
            ['district_id'=>'13', 'police_station_name'=>'Mohanganj Upazilla', 'police_station_bn_name'=>'মোহনগঞ্জ'],
            ['district_id'=>'13', 'police_station_name'=>'Netrakona-S Upazilla', 'police_station_bn_name'=>'নেত্রকোনা সদর'],
            ['district_id'=>'13', 'police_station_name'=>'Purbadhala Upazilla', 'police_station_bn_name'=>'পূর্বধলা'],
            ['district_id'=>'13', 'police_station_name'=>'Khaliajuri Upazilla', 'police_station_bn_name'=>'খালিয়াজুরি'],
            ['district_id'=>'14', 'police_station_name'=>'Baliakandi Upazila', 'police_station_bn_name'=>'বালিয়াকান্দি'],
            ['district_id'=>'14', 'police_station_name'=>'Goalandaghat Upazila', 'police_station_bn_name'=>'গোয়ালন্দ ঘাট'],
            ['district_id'=>'14', 'police_station_name'=>'Pangsha Upazila', 'police_station_bn_name'=>'পাংশা'],
            ['district_id'=>'14', 'police_station_name'=>'Kalukhali Upazila', 'police_station_bn_name'=>'কালুখালি'],
            ['district_id'=>'14', 'police_station_name'=>'Rajbari Sadar Upazila', 'police_station_bn_name'=>'রাজবাড়ি সদর'],
            ['district_id'=>'15', 'police_station_name'=>'Shariatpur Sadar -Palong', 'police_station_bn_name'=>'শরীয়তপুর সদর '],
            ['district_id'=>'15', 'police_station_name'=>'Damudya Upazila', 'police_station_bn_name'=>'দামুদিয়া'],
            ['district_id'=>'15', 'police_station_name'=>'Naria Upazila', 'police_station_bn_name'=>'নড়িয়া'],
            ['district_id'=>'15', 'police_station_name'=>'Jajira Upazila', 'police_station_bn_name'=>'জাজিরা'],
            ['district_id'=>'15', 'police_station_name'=>'Bhedarganj Upazila', 'police_station_bn_name'=>'ভেদারগঞ্জ'],
            ['district_id'=>'15', 'police_station_name'=>'Gosairhat Upazila', 'police_station_bn_name'=>'গোসাইর হাট '],
            ['district_id'=>'16', 'police_station_name'=>'Jhenaigati Upazila', 'police_station_bn_name'=>'ঝিনাইগাতি'],
            ['district_id'=>'16', 'police_station_name'=>'Nakla Upazila', 'police_station_bn_name'=>'নাকলা'],
            ['district_id'=>'16', 'police_station_name'=>'Nalitabari Upazila', 'police_station_bn_name'=>'নালিতাবাড়ি'],
            ['district_id'=>'16', 'police_station_name'=>'Sherpur Sadar Upazila', 'police_station_bn_name'=>'শেরপুর সদর'],
            ['district_id'=>'16', 'police_station_name'=>'Sreebardi Upazila', 'police_station_bn_name'=>'শ্রীবরদি'],
            ['district_id'=>'17', 'police_station_name'=>'Tangail Sadar Upazila', 'police_station_bn_name'=>'টাঙ্গাইল সদর'],
            ['district_id'=>'17', 'police_station_name'=>'Sakhipur Upazila', 'police_station_bn_name'=>'সখিপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Basail Upazila', 'police_station_bn_name'=>'বসাইল'],
            ['district_id'=>'17', 'police_station_name'=>'Madhupur Upazila', 'police_station_bn_name'=>'মধুপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Ghatail Upazila', 'police_station_bn_name'=>'ঘাটাইল'],
            ['district_id'=>'17', 'police_station_name'=>'Kalihati Upazila', 'police_station_bn_name'=>'কালিহাতি'],
            ['district_id'=>'17', 'police_station_name'=>'Nagarpur Upazila', 'police_station_bn_name'=>'নগরপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Mirzapur Upazila', 'police_station_bn_name'=>'মির্জাপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Gopalpur Upazila', 'police_station_bn_name'=>'গোপালপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Delduar Upazila', 'police_station_bn_name'=>'দেলদুয়ার'],
            ['district_id'=>'17', 'police_station_name'=>'Bhuapur Upazila', 'police_station_bn_name'=>'ভুয়াপুর'],
            ['district_id'=>'17', 'police_station_name'=>'Dhanbari Upazila', 'police_station_bn_name'=>'ধানবাড়ি'],
            ['district_id'=>'55', 'police_station_name'=>'Bagerhat Sadar Upazila', 'police_station_bn_name'=>'বাগেরহাট সদর'],
            ['district_id'=>'55', 'police_station_name'=>'Chitalmari Upazila', 'police_station_bn_name'=>'চিতলমাড়ি'],
            ['district_id'=>'55', 'police_station_name'=>'Fakirhat Upazila', 'police_station_bn_name'=>'ফকিরহাট'],
            ['district_id'=>'55', 'police_station_name'=>'Kachua Upazila', 'police_station_bn_name'=>'কচুয়া'],
            ['district_id'=>'55', 'police_station_name'=>'Mollahat Upazila', 'police_station_bn_name'=>'মোল্লাহাট '],
            ['district_id'=>'55', 'police_station_name'=>'Mongla Upazila', 'police_station_bn_name'=>'মংলা'],
            ['district_id'=>'55', 'police_station_name'=>'Morrelganj Upazila', 'police_station_bn_name'=>'মরেলগঞ্জ'],
            ['district_id'=>'55', 'police_station_name'=>'Rampal Upazila', 'police_station_bn_name'=>'রামপাল'],
            ['district_id'=>'55', 'police_station_name'=>'Sarankhola Upazila', 'police_station_bn_name'=>'স্মরণখোলা'],
            ['district_id'=>'56', 'police_station_name'=>'Damurhuda Upazila', 'police_station_bn_name'=>'দামুরহুদা'],
            ['district_id'=>'56', 'police_station_name'=>'Chuadanga-S Upazila', 'police_station_bn_name'=>'চুয়াডাঙ্গা সদর'],
            ['district_id'=>'56', 'police_station_name'=>'Jibannagar Upazila', 'police_station_bn_name'=>'জীবন নগর '],
            ['district_id'=>'56', 'police_station_name'=>'Alamdanga Upazila', 'police_station_bn_name'=>'আলমডাঙ্গা'],
            ['district_id'=>'57', 'police_station_name'=>'Abhaynagar Upazila', 'police_station_bn_name'=>'অভয়নগর'],
            ['district_id'=>'57', 'police_station_name'=>'Keshabpur Upazila', 'police_station_bn_name'=>'কেশবপুর'],
            ['district_id'=>'57', 'police_station_name'=>'Bagherpara Upazila', 'police_station_bn_name'=>'বাঘের পাড়া '],
            ['district_id'=>'57', 'police_station_name'=>'Jessore Sadar Upazila', 'police_station_bn_name'=>'যশোর সদর'],
            ['district_id'=>'57', 'police_station_name'=>'Chaugachha Upazila', 'police_station_bn_name'=>'চৌগাছা'],
            ['district_id'=>'57', 'police_station_name'=>'Manirampur Upazila', 'police_station_bn_name'=>'মনিরামপুর '],
            ['district_id'=>'57', 'police_station_name'=>'Jhikargachha Upazila', 'police_station_bn_name'=>'ঝিকরগাছা'],
            ['district_id'=>'57', 'police_station_name'=>'Sharsha Upazila', 'police_station_bn_name'=>'সারশা'],
            ['district_id'=>'58', 'police_station_name'=>'Jhenaidah Sadar Upazila', 'police_station_bn_name'=>'ঝিনাইদহ সদর'],
            ['district_id'=>'58', 'police_station_name'=>'Maheshpur Upazila', 'police_station_bn_name'=>'মহেশপুর'],
            ['district_id'=>'58', 'police_station_name'=>'Kaliganj Upazila', 'police_station_bn_name'=>'কালীগঞ্জ'],
            ['district_id'=>'58', 'police_station_name'=>'Kotchandpur Upazila', 'police_station_bn_name'=>'কোট চাঁদপুর '],
            ['district_id'=>'58', 'police_station_name'=>'Shailkupa Upazila', 'police_station_bn_name'=>'শৈলকুপা'],
            ['district_id'=>'58', 'police_station_name'=>'Harinakunda Upazila', 'police_station_bn_name'=>'হাড়িনাকুন্দা'],
            ['district_id'=>'59', 'police_station_name'=>'Terokhada Upazila', 'police_station_bn_name'=>'তেরোখাদা'],
            ['district_id'=>'59', 'police_station_name'=>'Batiaghata Upazila', 'police_station_bn_name'=>'বাটিয়াঘাটা '],
            ['district_id'=>'59', 'police_station_name'=>'Dacope Upazila', 'police_station_bn_name'=>'ডাকপে'],
            ['district_id'=>'59', 'police_station_name'=>'Dumuria Upazila', 'police_station_bn_name'=>'ডুমুরিয়া'],
            ['district_id'=>'59', 'police_station_name'=>'Dighalia Upazila', 'police_station_bn_name'=>'দিঘলিয়া'],
            ['district_id'=>'59', 'police_station_name'=>'Koyra Upazila', 'police_station_bn_name'=>'কয়ড়া'],
            ['district_id'=>'59', 'police_station_name'=>'Paikgachha Upazila', 'police_station_bn_name'=>'পাইকগাছা'],
            ['district_id'=>'59', 'police_station_name'=>'Phultala Upazila', 'police_station_bn_name'=>'ফুলতলা'],
            ['district_id'=>'59', 'police_station_name'=>'Rupsa Upazila', 'police_station_bn_name'=>'রূপসা'],
            ['district_id'=>'60', 'police_station_name'=>'Kushtia Sadar', 'police_station_bn_name'=>'কুষ্টিয়া সদর'],
            ['district_id'=>'60', 'police_station_name'=>'Kumarkhali', 'police_station_bn_name'=>'কুমারখালি'],
            ['district_id'=>'60', 'police_station_name'=>'Daulatpur', 'police_station_bn_name'=>'দৌলতপুর'],
            ['district_id'=>'60', 'police_station_name'=>'Mirpur', 'police_station_bn_name'=>'মিরপুর'],
            ['district_id'=>'60', 'police_station_name'=>'Bheramara', 'police_station_bn_name'=>'ভেরামারা'],
            ['district_id'=>'60', 'police_station_name'=>'Khoksa', 'police_station_bn_name'=>'খোকসা'],
            ['district_id'=>'61', 'police_station_name'=>'Magura Sadar Upazila', 'police_station_bn_name'=>'মাগুরা সদর'],
            ['district_id'=>'61', 'police_station_name'=>'Mohammadpur Upazila', 'police_station_bn_name'=>'মোহাম্মাদপুর'],
            ['district_id'=>'61', 'police_station_name'=>'Shalikha Upazila', 'police_station_bn_name'=>'শালিখা'],
            ['district_id'=>'61', 'police_station_name'=>'Sreepur Upazila', 'police_station_bn_name'=>'শ্রীপুর'],
            ['district_id'=>'62', 'police_station_name'=>'angni Upazila', 'police_station_bn_name'=>'আংনি'],
            ['district_id'=>'62', 'police_station_name'=>'Mujib Nagar Upazila', 'police_station_bn_name'=>'মুজিব নগর'],
            ['district_id'=>'62', 'police_station_name'=>'Meherpur-S Upazila', 'police_station_bn_name'=>'মেহেরপুর সদর'],
            ['district_id'=>'63', 'police_station_name'=>'Narail-S Upazilla', 'police_station_bn_name'=>'নড়াইল সদর'],
            ['district_id'=>'63', 'police_station_name'=>'Lohagara Upazilla', 'police_station_bn_name'=>'লোহাগাড়া'],
            ['district_id'=>'63', 'police_station_name'=>'Kalia Upazilla', 'police_station_bn_name'=>'কালিয়া'],
            ['district_id'=>'64', 'police_station_name'=>'Satkhira Sadar Upazila', 'police_station_bn_name'=>'সাতক্ষীরা সদর'],
            ['district_id'=>'64', 'police_station_name'=>'Assasuni Upazila', 'police_station_bn_name'=>'আসসাশুনি '],
            ['district_id'=>'64', 'police_station_name'=>'Debhata Upazila', 'police_station_bn_name'=>'দেভাটা'],
            ['district_id'=>'64', 'police_station_name'=>'Tala Upazila', 'police_station_bn_name'=>'তালা'],
            ['district_id'=>'64', 'police_station_name'=>'Kalaroa Upazila', 'police_station_bn_name'=>'কলরোয়া'],
            ['district_id'=>'64', 'police_station_name'=>'Kaliganj Upazila', 'police_station_bn_name'=>'কালীগঞ্জ'],
            ['district_id'=>'64', 'police_station_name'=>'Shyamnagar Upazila', 'police_station_bn_name'=>'শ্যামনগর'],
            ['district_id'=>'18', 'police_station_name'=>'Adamdighi', 'police_station_bn_name'=>'আদমদিঘী'],
            ['district_id'=>'18', 'police_station_name'=>'Bogra Sadar', 'police_station_bn_name'=>'বগুড়া সদর'],
            ['district_id'=>'18', 'police_station_name'=>'Sherpur', 'police_station_bn_name'=>'শেরপুর'],
            ['district_id'=>'18', 'police_station_name'=>'Dhunat', 'police_station_bn_name'=>'ধুনট'],
            ['district_id'=>'18', 'police_station_name'=>'Dhupchanchia', 'police_station_bn_name'=>'দুপচাচিয়া'],
            ['district_id'=>'18', 'police_station_name'=>'Gabtali', 'police_station_bn_name'=>'গাবতলি'],
            ['district_id'=>'18', 'police_station_name'=>'Kahaloo', 'police_station_bn_name'=>'কাহালু'],
            ['district_id'=>'18', 'police_station_name'=>'Nandigram', 'police_station_bn_name'=>'নন্দিগ্রাম'],
            ['district_id'=>'18', 'police_station_name'=>'Sahajanpur', 'police_station_bn_name'=>'শাহজাহানপুর'],
            ['district_id'=>'18', 'police_station_name'=>'Sariakandi', 'police_station_bn_name'=>'সারিয়াকান্দি'],
            ['district_id'=>'18', 'police_station_name'=>'Shibganj', 'police_station_bn_name'=>'শিবগঞ্জ'],
            ['district_id'=>'18', 'police_station_name'=>'Sonatala', 'police_station_bn_name'=>'সোনাতলা'],
            ['district_id'=>'19', 'police_station_name'=>'Joypurhat S', 'police_station_bn_name'=>'জয়পুরহাট সদর'],
            ['district_id'=>'19', 'police_station_name'=>'Akkelpur', 'police_station_bn_name'=>'আক্কেলপুর'],
            ['district_id'=>'19', 'police_station_name'=>'Kalai', 'police_station_bn_name'=>'কালাই'],
            ['district_id'=>'19', 'police_station_name'=>'Khetlal', 'police_station_bn_name'=>'খেতলাল'],
            ['district_id'=>'19', 'police_station_name'=>'Panchbibi', 'police_station_bn_name'=>'পাঁচবিবি'],
            ['district_id'=>'20', 'police_station_name'=>'Naogaon Sadar Upazila', 'police_station_bn_name'=>'নওগাঁ সদর'],
            ['district_id'=>'20', 'police_station_name'=>'Mohadevpur Upazila', 'police_station_bn_name'=>'মহাদেবপুর'],
            ['district_id'=>'20', 'police_station_name'=>'Manda Upazila', 'police_station_bn_name'=>'মান্দা'],
            ['district_id'=>'20', 'police_station_name'=>'Niamatpur Upazila', 'police_station_bn_name'=>'নিয়ামতপুর'],
            ['district_id'=>'20', 'police_station_name'=>'Atrai Upazila', 'police_station_bn_name'=>'আত্রাই'],
            ['district_id'=>'20', 'police_station_name'=>'Raninagar Upazila', 'police_station_bn_name'=>'রাণীনগর'],
            ['district_id'=>'20', 'police_station_name'=>'Patnitala Upazila', 'police_station_bn_name'=>'পত্নীতলা'],
            ['district_id'=>'20', 'police_station_name'=>'Dhamoirhat Upazila', 'police_station_bn_name'=>'ধামইরহাট '],
            ['district_id'=>'20', 'police_station_name'=>'Sapahar Upazila', 'police_station_bn_name'=>'সাপাহার'],
            ['district_id'=>'20', 'police_station_name'=>'Porsha Upazila', 'police_station_bn_name'=>'পোরশা'],
            ['district_id'=>'20', 'police_station_name'=>'Badalgachhi Upazila', 'police_station_bn_name'=>'বদলগাছি'],
            ['district_id'=>'21', 'police_station_name'=>'Natore Sadar Upazila', 'police_station_bn_name'=>'নাটোর সদর'],
            ['district_id'=>'21', 'police_station_name'=>'Baraigram Upazila', 'police_station_bn_name'=>'বড়াইগ্রাম'],
            ['district_id'=>'21', 'police_station_name'=>'Bagatipara Upazila', 'police_station_bn_name'=>'বাগাতিপাড়া'],
            ['district_id'=>'21', 'police_station_name'=>'Lalpur Upazila', 'police_station_bn_name'=>'লালপুর'],
            ['district_id'=>'21', 'police_station_name'=>'Natore Sadar Upazila', 'police_station_bn_name'=>'নাটোর সদর'],
            ['district_id'=>'21', 'police_station_name'=>'Baraigram Upazila', 'police_station_bn_name'=>'বড়াই গ্রাম'],
            ['district_id'=>'22', 'police_station_name'=>'Bholahat Upazila', 'police_station_bn_name'=>'ভোলাহাট'],
            ['district_id'=>'22', 'police_station_name'=>'Gomastapur Upazila', 'police_station_bn_name'=>'গোমস্তাপুর'],
            ['district_id'=>'22', 'police_station_name'=>'Nachole Upazila', 'police_station_bn_name'=>'নাচোল'],
            ['district_id'=>'22', 'police_station_name'=>'Nawabganj Sadar Upazila', 'police_station_bn_name'=>'নবাবগঞ্জ সদর'],
            ['district_id'=>'22', 'police_station_name'=>'Shibganj Upazila', 'police_station_bn_name'=>'শিবগঞ্জ'],
            ['district_id'=>'23', 'police_station_name'=>'Atgharia Upazila', 'police_station_bn_name'=>'আটঘরিয়া'],
            ['district_id'=>'23', 'police_station_name'=>'Bera Upazila', 'police_station_bn_name'=>'বেড়া'],
            ['district_id'=>'23', 'police_station_name'=>'Bhangura Upazila', 'police_station_bn_name'=>'ভাঙ্গুরা'],
            ['district_id'=>'23', 'police_station_name'=>'Chatmohar Upazila', 'police_station_bn_name'=>'চাটমোহর'],
            ['district_id'=>'23', 'police_station_name'=>'Faridpur Upazila', 'police_station_bn_name'=>'ফরিদপুর'],
            ['district_id'=>'23', 'police_station_name'=>'Ishwardi Upazila', 'police_station_bn_name'=>'ঈশ্বরদী'],
            ['district_id'=>'23', 'police_station_name'=>'Pabna Sadar Upazila', 'police_station_bn_name'=>'পাবনা সদর'],
            ['district_id'=>'23', 'police_station_name'=>'Santhia Upazila', 'police_station_bn_name'=>'সাথিয়া'],
            ['district_id'=>'23', 'police_station_name'=>'Sujanagar Upazila', 'police_station_bn_name'=>'সুজানগর'],
            ['district_id'=>'24', 'police_station_name'=>'Bagha', 'police_station_bn_name'=>'বাঘা'],
            ['district_id'=>'24', 'police_station_name'=>'Bagmara', 'police_station_bn_name'=>'বাগমারা'],
            ['district_id'=>'24', 'police_station_name'=>'Charghat', 'police_station_bn_name'=>'চারঘাট'],
            ['district_id'=>'24', 'police_station_name'=>'Durgapur', 'police_station_bn_name'=>'দুর্গাপুর'],
            ['district_id'=>'24', 'police_station_name'=>'Godagari', 'police_station_bn_name'=>'গোদাগারি'],
            ['district_id'=>'24', 'police_station_name'=>'Mohanpur', 'police_station_bn_name'=>'মোহনপুর'],
            ['district_id'=>'24', 'police_station_name'=>'Paba', 'police_station_bn_name'=>'পবা'],
            ['district_id'=>'24', 'police_station_name'=>'Puthia', 'police_station_bn_name'=>'পুঠিয়া'],
            ['district_id'=>'24', 'police_station_name'=>'Tanore', 'police_station_bn_name'=>'তানোর'],
            ['district_id'=>'25', 'police_station_name'=>'Sirajganj Sadar Upazila', 'police_station_bn_name'=>'সিরাজগঞ্জ সদর'],
            ['district_id'=>'25', 'police_station_name'=>'Belkuchi Upazila', 'police_station_bn_name'=>'বেলকুচি'],
            ['district_id'=>'25', 'police_station_name'=>'Chauhali Upazila', 'police_station_bn_name'=>'চৌহালি'],
            ['district_id'=>'25', 'police_station_name'=>'Kamarkhanda Upazila', 'police_station_bn_name'=>'কামারখান্দা'],
            ['district_id'=>'25', 'police_station_name'=>'Kazipur Upazila', 'police_station_bn_name'=>'কাজীপুর'],
            ['district_id'=>'25', 'police_station_name'=>'Raiganj Upazila', 'police_station_bn_name'=>'রায়গঞ্জ'],
            ['district_id'=>'25', 'police_station_name'=>'Shahjadpur Upazila', 'police_station_bn_name'=>'শাহজাদপুর'],
            ['district_id'=>'25', 'police_station_name'=>'Tarash Upazila', 'police_station_bn_name'=>'তারাশ'],
            ['district_id'=>'25', 'police_station_name'=>'Ullahpara Upazila', 'police_station_bn_name'=>'উল্লাপাড়া'],
            ['district_id'=>'26', 'police_station_name'=>'Birampur Upazila', 'police_station_bn_name'=>'বিরামপুর'],
            ['district_id'=>'26', 'police_station_name'=>'Birganj', 'police_station_bn_name'=>'বীরগঞ্জ'],
            ['district_id'=>'26', 'police_station_name'=>'Biral Upazila', 'police_station_bn_name'=>'বিড়াল'],
            ['district_id'=>'26', 'police_station_name'=>'Bochaganj Upazila', 'police_station_bn_name'=>'বোচাগঞ্জ'],
            ['district_id'=>'26', 'police_station_name'=>'Chirirbandar Upazila', 'police_station_bn_name'=>'চিরিরবন্দর'],
            ['district_id'=>'26', 'police_station_name'=>'Phulbari Upazila', 'police_station_bn_name'=>'ফুলবাড়ি'],
            ['district_id'=>'26', 'police_station_name'=>'Ghoraghat Upazila', 'police_station_bn_name'=>'ঘোড়াঘাট'],
            ['district_id'=>'26', 'police_station_name'=>'Hakimpur Upazila', 'police_station_bn_name'=>'হাকিমপুর'],
            ['district_id'=>'26', 'police_station_name'=>'Kaharole Upazila', 'police_station_bn_name'=>'কাহারোল'],
            ['district_id'=>'26', 'police_station_name'=>'Khansama Upazila', 'police_station_bn_name'=>'খানসামা'],
            ['district_id'=>'26', 'police_station_name'=>'Dinajpur Sadar Upazila', 'police_station_bn_name'=>'দিনাজপুর সদর'],
            ['district_id'=>'26', 'police_station_name'=>'Nawabganj', 'police_station_bn_name'=>'নবাবগঞ্জ'],
            ['district_id'=>'26', 'police_station_name'=>'Parbatipur Upazila', 'police_station_bn_name'=>'পার্বতীপুর'],
            ['district_id'=>'27', 'police_station_name'=>'Fulchhari', 'police_station_bn_name'=>'ফুলছড়ি'],
            ['district_id'=>'27', 'police_station_name'=>'Gaibandha sadar', 'police_station_bn_name'=>'গাইবান্ধা সদর'],
            ['district_id'=>'27', 'police_station_name'=>'Gobindaganj', 'police_station_bn_name'=>'গোবিন্দগঞ্জ'],
            ['district_id'=>'27', 'police_station_name'=>'Palashbari', 'police_station_bn_name'=>'পলাশবাড়ী'],
            ['district_id'=>'27', 'police_station_name'=>'Sadullapur', 'police_station_bn_name'=>'সাদুল্যাপুর'],
            ['district_id'=>'27', 'police_station_name'=>'Saghata', 'police_station_bn_name'=>'সাঘাটা'],
            ['district_id'=>'27', 'police_station_name'=>'Sundarganj', 'police_station_bn_name'=>'সুন্দরগঞ্জ'],
            ['district_id'=>'28', 'police_station_name'=>'Kurigram Sadar', 'police_station_bn_name'=>'কুড়িগ্রাম সদর'],
            ['district_id'=>'28', 'police_station_name'=>'Nageshwari', 'police_station_bn_name'=>'নাগেশ্বরী'],
            ['district_id'=>'28', 'police_station_name'=>'Bhurungamari', 'police_station_bn_name'=>'ভুরুঙ্গামারি'],
            ['district_id'=>'28', 'police_station_name'=>'Phulbari', 'police_station_bn_name'=>'ফুলবাড়ি'],
            ['district_id'=>'28', 'police_station_name'=>'Rajarhat', 'police_station_bn_name'=>'রাজারহাট'],
            ['district_id'=>'28', 'police_station_name'=>'Ulipur', 'police_station_bn_name'=>'উলিপুর'],
            ['district_id'=>'28', 'police_station_name'=>'Chilmari', 'police_station_bn_name'=>'চিলমারি'],
            ['district_id'=>'28', 'police_station_name'=>'Rowmari', 'police_station_bn_name'=>'রউমারি'],
            ['district_id'=>'28', 'police_station_name'=>'Char Rajibpur', 'police_station_bn_name'=>'চর রাজিবপুর'],
            ['district_id'=>'29', 'police_station_name'=>'Lalmanirhat Sadar', 'police_station_bn_name'=>'লালমনিরহাট সদর'],
            ['district_id'=>'29', 'police_station_name'=>'Aditmari', 'police_station_bn_name'=>'আদিতমারি'],
            ['district_id'=>'29', 'police_station_name'=>'Kaliganj', 'police_station_bn_name'=>'কালীগঞ্জ'],
            ['district_id'=>'29', 'police_station_name'=>'Hatibandha', 'police_station_bn_name'=>'হাতিবান্ধা'],
            ['district_id'=>'29', 'police_station_name'=>'Patgram', 'police_station_bn_name'=>'পাটগ্রাম'],
            ['district_id'=>'30', 'police_station_name'=>'Nilphamari Sadar', 'police_station_bn_name'=>'নীলফামারী সদর'],
            ['district_id'=>'30', 'police_station_name'=>'Saidpur', 'police_station_bn_name'=>'সৈয়দপুর'],
            ['district_id'=>'30', 'police_station_name'=>'Jaldhaka', 'police_station_bn_name'=>'জলঢাকা'],
            ['district_id'=>'30', 'police_station_name'=>'Kishoreganj', 'police_station_bn_name'=>'কিশোরগঞ্জ'],
            ['district_id'=>'30', 'police_station_name'=>'Domar', 'police_station_bn_name'=>'ডোমার'],
            ['district_id'=>'30', 'police_station_name'=>'Dimla', 'police_station_bn_name'=>'ডিমলা'],
            ['district_id'=>'31', 'police_station_name'=>'Panchagarh Sadar', 'police_station_bn_name'=>'পঞ্চগড় সদর'],
            ['district_id'=>'31', 'police_station_name'=>'Debiganj', 'police_station_bn_name'=>'দেবীগঞ্জ'],
            ['district_id'=>'31', 'police_station_name'=>'Boda', 'police_station_bn_name'=>'বোদা'],
            ['district_id'=>'31', 'police_station_name'=>'Atwari', 'police_station_bn_name'=>'আটোয়ারি'],
            ['district_id'=>'31', 'police_station_name'=>'Tetulia', 'police_station_bn_name'=>'তেতুলিয়া'],
            ['district_id'=>'32', 'police_station_name'=>'Badarganj', 'police_station_bn_name'=>'বদরগঞ্জ'],
            ['district_id'=>'32', 'police_station_name'=>'Mithapukur', 'police_station_bn_name'=>'মিঠাপুকুর'],
            ['district_id'=>'32', 'police_station_name'=>'Gangachara', 'police_station_bn_name'=>'গঙ্গাচরা'],
            ['district_id'=>'32', 'police_station_name'=>'Kaunia', 'police_station_bn_name'=>'কাউনিয়া'],
            ['district_id'=>'32', 'police_station_name'=>'Rangpur Sadar', 'police_station_bn_name'=>'রংপুর সদর'],
            ['district_id'=>'32', 'police_station_name'=>'Pirgachha', 'police_station_bn_name'=>'পীরগাছা'],
            ['district_id'=>'32', 'police_station_name'=>'Pirganj', 'police_station_bn_name'=>'পীরগঞ্জ'],
            ['district_id'=>'32', 'police_station_name'=>'Taraganj', 'police_station_bn_name'=>'তারাগঞ্জ'],
            ['district_id'=>'33', 'police_station_name'=>'Thakurgaon Sadar Upazila', 'police_station_bn_name'=>'ঠাকুরগাঁও সদর'],
            ['district_id'=>'33', 'police_station_name'=>'Pirganj Upazila', 'police_station_bn_name'=>'পীরগঞ্জ'],
            ['district_id'=>'33', 'police_station_name'=>'Baliadangi Upazila', 'police_station_bn_name'=>'বালিয়াডাঙ্গি'],
            ['district_id'=>'33', 'police_station_name'=>'Haripur Upazila', 'police_station_bn_name'=>'হরিপুর'],
            ['district_id'=>'33', 'police_station_name'=>'Ranisankail Upazila', 'police_station_bn_name'=>'রাণীসংকইল'],
            ['district_id'=>'51', 'police_station_name'=>'Ajmiriganj', 'police_station_bn_name'=>'আজমিরিগঞ্জ'],
            ['district_id'=>'51', 'police_station_name'=>'Baniachang', 'police_station_bn_name'=>'বানিয়াচং'],
            ['district_id'=>'51', 'police_station_name'=>'Bahubal', 'police_station_bn_name'=>'বাহুবল'],
            ['district_id'=>'51', 'police_station_name'=>'Chunarughat', 'police_station_bn_name'=>'চুনারুঘাট'],
            ['district_id'=>'51', 'police_station_name'=>'Habiganj Sadar', 'police_station_bn_name'=>'হবিগঞ্জ সদর'],
            ['district_id'=>'51', 'police_station_name'=>'Lakhai', 'police_station_bn_name'=>'লাক্ষাই'],
            ['district_id'=>'51', 'police_station_name'=>'Madhabpur', 'police_station_bn_name'=>'মাধবপুর'],
            ['district_id'=>'51', 'police_station_name'=>'Nabiganj', 'police_station_bn_name'=>'নবীগঞ্জ'],
            ['district_id'=>'51', 'police_station_name'=>'Shaistagonj Upazila', 'police_station_bn_name'=>'শায়েস্তাগঞ্জ'],
            ['district_id'=>'52', 'police_station_name'=>'Moulvibazar Sadar', 'police_station_bn_name'=>'মৌলভীবাজার'],
            ['district_id'=>'52', 'police_station_name'=>'Barlekha', 'police_station_bn_name'=>'বড়লেখা'],
            ['district_id'=>'52', 'police_station_name'=>'Juri', 'police_station_bn_name'=>'জুড়ি'],
            ['district_id'=>'52', 'police_station_name'=>'Kamalganj', 'police_station_bn_name'=>'কামালগঞ্জ'],
            ['district_id'=>'52', 'police_station_name'=>'Kulaura', 'police_station_bn_name'=>'কুলাউরা'],
            ['district_id'=>'52', 'police_station_name'=>'Rajnagar', 'police_station_bn_name'=>'রাজনগর'],
            ['district_id'=>'52', 'police_station_name'=>'Sreemangal', 'police_station_bn_name'=>'শ্রীমঙ্গল'],
            ['district_id'=>'53', 'police_station_name'=>'Bishwamvarpur', 'police_station_bn_name'=>'বিসশম্ভারপুর'],
            ['district_id'=>'53', 'police_station_name'=>'Chhatak', 'police_station_bn_name'=>'ছাতক'],
            ['district_id'=>'53', 'police_station_name'=>'Derai', 'police_station_bn_name'=>'দেড়াই'],
            ['district_id'=>'53', 'police_station_name'=>'Dharampasha', 'police_station_bn_name'=>'ধরমপাশা'],
            ['district_id'=>'53', 'police_station_name'=>'Dowarabazar', 'police_station_bn_name'=>'দোয়ারাবাজার'],
            ['district_id'=>'53', 'police_station_name'=>'Jagannathpur', 'police_station_bn_name'=>'জগন্নাথপুর'],
            ['district_id'=>'53', 'police_station_name'=>'Jamalganj', 'police_station_bn_name'=>'জামালগঞ্জ'],
            ['district_id'=>'53', 'police_station_name'=>'Sulla', 'police_station_bn_name'=>'সুল্লা'],
            ['district_id'=>'53', 'police_station_name'=>'Sunamganj Sadar', 'police_station_bn_name'=>'সুনামগঞ্জ সদর'],
            ['district_id'=>'53', 'police_station_name'=>'Shanthiganj', 'police_station_bn_name'=>'শান্তিগঞ্জ'],
            ['district_id'=>'53', 'police_station_name'=>'Tahirpur', 'police_station_bn_name'=>'তাহিরপুর'],
            ['district_id'=>'54', 'police_station_name'=>'Sylhet Sadar', 'police_station_bn_name'=>'সিলেট সদর'],
            ['district_id'=>'54', 'police_station_name'=>'Beanibazar', 'police_station_bn_name'=>'বেয়ানিবাজার'],
            ['district_id'=>'54', 'police_station_name'=>'Bishwanath', 'police_station_bn_name'=>'বিশ্বনাথ'],
            ['district_id'=>'54', 'police_station_name'=>'Dakshin Surma Upazila', 'police_station_bn_name'=>'দক্ষিণ সুরমা'],
            ['district_id'=>'54', 'police_station_name'=>'Balaganj', 'police_station_bn_name'=>'বালাগঞ্জ'],
            ['district_id'=>'54', 'police_station_name'=>'Companiganj', 'police_station_bn_name'=>'কোম্পানিগঞ্জ'],
            ['district_id'=>'54', 'police_station_name'=>'Fenchuganj', 'police_station_bn_name'=>'ফেঞ্চুগঞ্জ'],
            ['district_id'=>'54', 'police_station_name'=>'Golapganj', 'police_station_bn_name'=>'গোলাপগঞ্জ'],
            ['district_id'=>'54', 'police_station_name'=>'Gowainghat', 'police_station_bn_name'=>'গোয়াইনঘাট'],
            ['district_id'=>'54', 'police_station_name'=>'Jaintiapur', 'police_station_bn_name'=>'জয়ন্তপুর'],
            ['district_id'=>'54', 'police_station_name'=>'Kanaighat', 'police_station_bn_name'=>'কানাইঘাট'],
            ['district_id'=>'54', 'police_station_name'=>'Zakiganj', 'police_station_bn_name'=>'জাকিগঞ্জ'],
            ['district_id'=>'54', 'police_station_name'=>'Nobigonj', 'police_station_bn_name'=>'নবীগঞ্জ'],
            ['district_id'=>'1', 'police_station_name'=>'Tejgaon Circle', 'police_station_bn_name'=>'তেজগাঁও সার্কেল'],
            ['district_id'=>'21', 'police_station_name'=>'Gurudaspur', 'police_station_bn_name'=>'গুরুদাসপুর'],
        ]);
    }
}
